version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
        
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0/5 * * * *"
    # ignore:
    #   # Ignore patch updates for stability
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-patch"]
