#!/bin/sh

# Ensure X11 is used
export XDG_SESSION_DESKTOP=KDE-KWIN
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_TYPE=x11

# Ensure DBus socket is created and accessible
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
  eval `dbus-launch --sh-syntax --exit-with-session`
  echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" > ~/.dbus-session-bus-address-$(echo $(date +%s))
fi
export DBUS_SESSION_BUS_ADDRESS

# Start the KDE Plasma session
dbus-launch startplasma-x11