name: Build and push qcow2 image

on:
  workflow_dispatch:
  ## For testing
  push:
    branches: [ main ]
    # paths:
    #   - '.github/workflows/build-push.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: latest

jobs:  
  build-qcow2-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Install podman and qemu-utils
        run: |
          sudo apt update
          sudo apt install -y podman qemu-utils

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Pull Image
        id: pull-image
        env:
          INPUT_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        run: |
          sudo podman pull $INPUT_IMAGE

      - name: Create empty disk image
        run: qemu-img create -f qcow2 -o preallocation=metadata coreos-$(uname -m).qcow2 48G

      - name: Mount disk image as block device
        run: |
          sudo modprobe nbd
          sudo qemu-nbd -c /dev/nbd0 coreos-$(uname -m).qcow2

      - name: Create authorized_keys
        run: |
          touch authorized_keys
          printf ${{ secrets.SSH_PUBKEY }} > authorized_keys

      - name: Install image to disk
        id: bootc-install-to-disk
        env:
          INPUT_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        run: |
          docker run --rm --privileged -v /dev:/dev \
            --pid=host --security-opt label=type:unconfined_t \
            -v $(pwd)/authorized_keys:/tmp/authorized_keys \
            $INPUT_IMAGE \
            bootc install to-disk \
            --generic-image \
            --filesystem=btrfs \
            --source-imgref=docker://$INPUT_IMAGE \
            --target-imgref=docker://$INPUT_IMAGE \
            --root-ssh-authorized-keys=/tmp/pwd/authorized_keys \
            /dev/nbd0
            
      - name: Detach disk image
        run: sudo qemu-nbd -d /dev/nbd0

      - name: Upload to Backblaze
        id: upload-b2
        uses: yamatt/backblaze-b2-upload-action@v7
        with:
          key_id: ${{ secrets.B2_KEY_ID }}
          application_key: ${{ secrets.B2_APPLICATION_KEY }}
          bucket_name: ${{ secrets.B2_BUCKET_NAME }}
          file_path: coreos-$(uname -m).qcow2
          remote_path: artifacts/coreos-$(uname -m).qcow2