name: Build and Publish Container

on:
  push:
    branches: ['main'] # Only trigger on main now
    paths:
      - 'hci.Containerfile'
      - 'rootfs/hci/**'
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VARIENT: hci
  # BRANCH env var might be less relevant or repurposed

jobs:
  build-main-metadata: # Example for a "main" or "common" variant
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} # Default image
          tags: |
            type=raw,value=${{ env.VARIENT }}
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=pr
            type=schedule,pattern={{date 'YYYYMMDD'}}

  build-main: # Renamed from 'build' to be specific
    runs-on: ubuntu-24.04-arm
    needs: build-main-metadata
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile # Assumes this is for the main/common variant
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ needs.build-main-metadata.outputs.tags }}
          labels: ${{ needs.build-main-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
